### ISSUE TITLE
Error in if (grepl("^CM.+", volumeUnit))  

### ISSUE THREAD

**Issue by romasg** [dwoll/DVHmetrics#1]
Hello, 
I'm getting this error on macOS (under the windows is ok) when trying to read DVH. 

readDVH("~/dir/filename", type = "Eclipse")

Error in if (grepl("^CM.+", volumeUnit)) { : argument is of length zero
In addition: There were 19 warnings (use warnings() to see them)

Could you help me, and guide me out this issue. I'm new in R and DVHmetrics.

**Comment by dwoll** [comment]
Hi, without seeing your DVH file, my suspicion is that there is a problem with the line that contains the structure volume info with a superscript 3 in "cm^3". The  superscript 3 is a special character that requires proper encoding of the file (UTF-8) to be read correctly. Unfortunately, I do not have access to MacOS to confirm this suspicion, but I will probably be able to do so in a week.

Until then, what you can do is to either save the file from a text editor that can explicitly set the encoding to UTF-8. Or, you can replace all superscript 3 with regular 3 in a text editor, and try again.

Any success?

**Comment by romasg** [comment]
Hi, yes it solved the problem, line with Volume information displayed, 

`Volume` [cm≥]: `1044.3`

and symbol "≥" creates the problem. Everything is fine when it was replaced to "3".

Thanks.
