### ISSUE TITLE
NA returned from getNTCP()

### ISSUE THREAD

**Issue by MelAMcIntyre** [dwoll/DVHmetrics#12]
Hi there,

I am looking for some assistance with the NTCP calculation. `getNTCP()` is returning a NaN value for the attached DVH (from RayStation) with the following parameters.

```
> getNTCP(x=x[[1]], NTCPtd50=56, NTCPm=0.64, NTCPn=0.203, NTCPtype="probit")
  NTCP patID structure
1   NA    13   STOMACH
Warning message:
In getEUD.DVHs(x, EUDa = EUDa, EUDfn = EUDfn, EUDab = EUDab) :
  Numerical problems encountered, NA returned
```
I am wondering if you could point me in the right direction?

[photontest.txt](https://github.com/dwoll/DVHmetrics/files/12988349/photontest.txt)

**Comment by dwoll** [comment]
Hi Mel, Thank you for testing `DVHmetrics`! Currently, EUD calculation works with absolute volume only, so you have to supply information on structure volume when reading in the data via option `raystation` as follows:

```
x <- readDVH("/path/to/file.txt",
             type="RayStation",
             raystation=list(list(date="2023-10-21",
                                  doseRx="54Gy",
                                  volumeUnit="CC",
                                  structVol=c("STOMACH"=150))))
```

Please see https://github.com/dwoll/DVHmetrics/issues/6 for an example of reading in multiple files, or for having more than 1 structure per file.

Does this work?

**Comment by dwoll** [comment]
On second thought, I implemented gEUD calculation based on information on relative volume. If you do `remotes::install_github("dwoll/DVHmetrics")`, and run your code again, it should work. Feedback welcome!

**Comment by MelAMcIntyre** [comment]
Yes this has done the trick! Thank you so much for the quick response :)

> On second thought, I implemented gEUD calculation based on information on relative volume. If you do `remotes::install_github("dwoll/DVHmetrics")`, and run your code again, it should work. Feedback welcome!
