### ISSUE TITLE
HiArt file reading problem

### ISSUE THREAD

**Issue by Abood-Me** [dwoll/DVHmetrics#15]
[dvh.txt](https://github.com/dwoll/DVHmetrics/files/14453830/dvh.txt)

I'm getting this error:
`Error in (function (strIdx, dIdx, vIdx, info, structVol, doseRx)  : 
  isIncreasing(dvh) is not TRUE
In addition: Warning messages:
1: In (function (strIdx, dIdx, vIdx, info, structVol, doseRx)  :
  I assume differential DVH is per unit dose
but I have no information on this
2: In (function (strIdx, dIdx, vIdx, info, structVol, doseRx)  :
  I assume differential DVH is per unit dose
but I have no information on this`

**Comment by dwoll** [comment]
Hi, Thanks for providing a sample DVH file! The import routine fails because it is not prepared for reading numbers in the format "4.326174454782894E-4". I will have to fix that. It will take a couple of days as there's a couple of other things on my desk at the moment.

**Comment by sudo-bluee** [comment]
I tried replacing numbers with that format to 0.000000000000000000 I get less warnings now but still have the error : 
`Error in (function (strIdx, dIdx, vIdx, info, structVol, doseRx)  : 
  isIncreasing(dvh) is not TRUE`

**Comment by Abood-Me** [comment]
I tried replacing numbers with that format to 0.000000000000000000, i get less warnings but still have error:
```
Error in (function (strIdx, dIdx, vIdx, info, structVol, doseRx)  : 
  isIncreasing(dvh) is not TRUE
```
  
Sorry for the miss click closing the issue.

**Comment by dwoll** [comment]
Hi, can you check again using the development version from GitHub?

```
install.packages("remotes")  # to install from GitHub
remotes::install_github("dwoll/DVHmetrics")
library(DVHmetrics)
x <- readDVH("path/to/file", type="HiArt")
```

**Comment by Abood-Me** [comment]
Yes, it works greats, Thank you for your responsiveness
