### ISSUE TITLE
  installation of package ‘shiny’ had non-zero exit status

### ISSUE THREAD

**Issue by robmarkcole** [dwoll/DVHmetrics#2]
## After updating packages on 12/9/2016, I now get an error when importing DVHmetrics. Previously this had worked fine.

> library(DVHmetrics, verbose=FALSE)

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘shiny’
Error: package or namespace load failed for ‘DVHmetrics’
## I then attempt to install shiny

> install.packages("shiny")

trying URL 'https://cran.rstudio.com/src/contrib/shiny_0.14.tar.gz'
Content type 'application/x-gzip' length 2110934 bytes (2.0 MB)
downloaded 2.0 MB

ERROR: dependency 'sourcetools' is not available for package 'shiny'
- removing 'C:/R/R-3.3.1/library/shiny'

Warning in install.packages :
  running command '"C:/R/R-33~1.1/bin/i386/R" CMD INSTALL -l "C:\R\R-3.3.1\library" 

C:\Users..../downloaded_packages/shiny_0.14.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘shiny’ had non-zero exit status

**Comment by dwoll** [comment]
It appears that package `sourcetools` was added as a dependency for `shiny` 0.14. Usually, `update.packages()` should take care of installing these added dependencies automatically. This worked on my installation, but you may try to `install.packages(c("sourcetools", "shiny"))` manually. Does this work? If not, are you using Windows, MacOS or Linux?

On my installation, `DVHmetrics` continues to work with `shiny` 0.14.

**Comment by robmarkcole** [comment]
### It could be an issue with my setup, since I am using a work laptop (Win 7) to which I do not have admin rights, but login as a user. When I try the manual install I get an error:

`install.packages("C:\Users\xxxxxxx\AppData\Local\Temp\RtmpOyBdEt\downloaded_packages/shiny_0.14.tar.gz", repos = NULL, type="source")`

### and

`install.packages('shiny', repos = 'C:\Users\XXXXXXXXX\AppData\Local\Temp\RtmpOyBdEt\downloaded_packages', type="source")`

`Error: '\U' used without hex digits in character string starting "'C:\U"`

### This is mentioned online but no solution is offered:

http://stackoverflow.com/questions/33662201/r-on-windows-compile-errors-u-used-without-hex-digits

### I then try:

`install.packages("C:\\Users\\xxx\\AppData\\Local\\Temp\\RtmpOyBdEt\\downloaded_packages/shiny_0.14.tar.gz", repos = NULL, type="source")`

### And get:

'\xxx-userdata\h_drive\xxx'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
ERROR: dependency 'sourcetools' is not available for package 'shiny', removing 'C:/R/R-3.3.1/library/shiny'

Warning in install.packages :
  running command '"C:/R/R-33~1.1/bin/i386/R" CMD INSTALL -l "C:\R\R-3.3.1\library" "C:/Users/xxx/AppData/Local/Temp/RtmpOyBdEt/downloaded_packages/shiny_0.14.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/xxx/AppData/Local/Temp/RtmpOyBdEt/downloaded_packages/shiny_0.14.tar.gz’ had non-zero exit status`

**Comment by dwoll** [comment]
You are trying to install the packages from source which may cause additional difficulties. I'd try installing binaries. Note that it may take CRAN a few days until the current version of `sourcetools` is available for Windows as a binary package.

**Comment by pthakur4** [comment]
can someone please help on this error, I have tried a lot but unable to.
see the below error - 

trying URL 'https://cloud.r-project.org/src/contrib/shiny_1.0.5.tar.gz'
Content type 'application/x-gzip' length 2330710 bytes (2.2 MB)
downloaded 2.2 MB

* installing *source* package 'shiny' ...
** package 'shiny' successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'httpuv' 1.3.3 is being loaded, but >= 1.3.5 is required
ERROR: lazy loading failed for package 'shiny'
* removing 'C:/SWDTOOLS/Rtools/win-library/3.2/shiny'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.5/bin/x64/R" CMD INSTALL -l "C:\SWDTOOLS\Rtools\win-library\3.2" C:\Users\44062934\AppData\Local\Temp\RtmpKMfMEG/downloaded_packages/shiny_1.0.5.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘shiny’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\USER\AppData\Local\Temp\RtmpKMfMEG\downloaded_packages’

**Comment by pthakur4** [comment]
I tried installing devtools as well but still no luck. devtools also giving error. 

 devtools::install_github("rstudio/shiny")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't resolve host name
Calls: <Anonymous> ... request_fetch -> request_fetch.write_disk -> <Anonymous> -> .Call

Enter a frame number, or 0 to exit   

 1: devtools::install_github("rstudio/shiny")
 2: install_remotes(remotes, quiet = quiet, ...)
 3: vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
 4: FUN(X[[i]], ...)
 5: remote_package_name(remote)
 6: remote_package_name.github_remote(remote)
 7: httr::GET(url, path = path, httr::write_disk(path = tmp))
 8: request_perform(req, hu$handle$handle)
 9: request_fetch(req$output, req$url, handle)
10: request_fetch.write_disk(req$output, req$url, handle)
11: curl::curl_fetch_disk(url, x$path, handle = handle)

Selection: 0

**Comment by dwoll** [comment]
The error message indicates that your installed version of package httpuv is too old: It's 1.3.3, but 1.3.5 is required. You may try to run `install.packages("httpuv")` first before installing shiny and DVHmetrics. The error when installing devtools might have something to with it, too.

**Comment by pthakur4** [comment]
Tried installing by downloading the httpuv version 1.3.5 - but this gives error too.

Installing package into ‘C:/SWDTOOLS/Rtools/win-library/3.2’
(as ‘lib’ is unspecified)
* installing *source* package 'httpuv' ...
** package 'httpuv' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-32~1.5/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.5/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="httpuv.dll" OBJECTS="RcppExports.o filedatasource-unix.o filedatasource-win.o http.o httpuv.o md5.o register.o set_invalid_parameter.o uvutil.o websockets-base.o websockets-hixie76.o websockets-hybi03.o websockets-ietf.o websockets.o"' had status 127
ERROR: compilation failed for package 'httpuv'
* removing 'C:/SWDTOOLS/Rtools/win-library/3.2/httpuv'
* restoring previous 'C:/SWDTOOLS/Rtools/win-library/3.2/httpuv'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.5/bin/x64/R" CMD INSTALL -l "C:\SWDTOOLS\Rtools\win-library\3.2" "C:/Users/44062934/Downloads/httpuv_1.3.5.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/USER/Downloads/httpuv_1.3.5.tar.gz’ had non-zero exit status

**Comment by dwoll** [comment]
Maybe trying to install the pre-compiled binary version of `httpuv` works? `install.packages("httpuv", type="binary")`

**Comment by koolaquarian213** [comment]
@dwoll Your suggestion worked for me!! I was getting the exact error message that @pthakur4 was getting. I ran install.packages("shiny", type="binary"). It got installed without any issues!

install.packages('shiny', type = "binary")
Installing package into ‘C:/Users/username/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

  There is a binary version available (and will be installed) but the source version is later:
      binary source
shiny  1.0.2  1.0.5

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/shiny_1.0.2.zip'
Content type 'application/zip' length 2755919 bytes (2.6 MB)
downloaded 2.6 MB

package ‘shiny’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\username\AppData\Local\Temp\Rtmpqy74Pn\downloaded_packages
> library('shiny')
Warning message:
package ‘shiny’ was built under R version 3.2.5

**Comment by rezwanh001** [comment]
I am getting this error . How can I solve it ?

```
install.packages("mlbench")
trying URL 'https://cran.rstudio.com/src/contrib/mlbench_2.1-1.tar.gz'
Content type 'application/x-gzip' length 920768 bytes (899 KB)
==================================================
downloaded 899 KB

* installing *source* package ‘mlbench’ ...
** package ‘mlbench’ successfully unpacked and MD5 sums checked
** libs
/home/rezwan/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -I/home/rezwan/anaconda3/lib/R/include -DNDEBUG   -D_FORTIFY_SOURCE=2 -O2 -I/home/rezwan/anaconda3/include   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/rezwan/anaconda3/include  -c waveform.c -o waveform.o
make: /home/rezwan/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc: Command not found
/home/rezwan/anaconda3/lib/R/etc/Makeconf:160: recipe for target 'waveform.o' failed
make: *** [waveform.o] Error 127
ERROR: compilation failed for package ‘mlbench’
* removing ‘/home/rezwan/anaconda3/lib/R/library/mlbench’
Warning in install.packages :
  installation of package ‘mlbench’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpoIHfXL/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

```

**Comment by dwoll** [comment]
This issue does not seem to be related to `DVHmetrics`. However, googling the error message "x86_64-conda_cos6-linux-gnu-cc: Command not found" gives a number of hits, one of them [https://stackoverflow.com/a/46457813/484139](https://stackoverflow.com/a/46457813/484139) - indicating that there is a problem in the configuration of Anaconda.

**Comment by paulmattheww** [comment]
This worked for me.

`install.packages('httpuv', type='binary')`
`install.packages('shiny', type='binary')`

**Comment by mratyunjay007** [comment]
this works for me too

**Comment by snajar01** [comment]
install.packages('shiny', type='binary') worked for me, but a version behind

**Comment by Acassarino** [comment]
install.packages("shiny", type="binary") worked for me too!! Thanks.

**Comment by Hello-Sarah** [comment]
install.packages("shiny", type="binary")  worked for me too!!! Thank you so much!

**Comment by shubhamsendre** [comment]
This worked for me as well. Thanks a lot for help.

**Comment by igorfarah** [comment]
> This worked for me.
> 
> `install.packages('httpuv', type='binary')`
> `install.packages('shiny', type='binary')`

Worked for me

**Comment by ksuraj93** [comment]
The fix install.packages("shiny", type="binary"). worked for me as well. Thanks a a lot

**Comment by Kim961824** [comment]
![image](https://user-images.githubusercontent.com/80138634/110192316-396bd980-7e68-11eb-8ee6-89be4e46a0f0.png)

Any help would be great appreciated

**Comment by BrigitteGUILLON** [comment]
Work for me , thanks a lot ...

**Comment by y3rawat** [comment]
> install.packages("httpuv", type="binary")
Error in install.packages : type 'binary' is not supported on this platform

not worked for me 
I'm in ubuntu OS

**Comment by dwoll** [comment]
`type="binary'` only works on Windows and MacOS as CRAN offers pre-compiled binary packages for these platforms (https://cran.r-project.org/package=httpuv). On Ubuntu, you have to either install from source using `type="source"`, or install the package outside of R using the Ubuntu package manager. On the command line, it could be something like `sudo apt-get install r-cran-httpuv` - though I haven't checked that.
