### ISSUE TITLE
SO question regarding legend

### ISSUE THREAD

**Issue by zx8754** [dwoll/DVHmetrics#3]
I posted below answer at SO:
https://stackoverflow.com/a/47138475/680068

Any better way of doing this?

**Comment by dwoll** [comment]
Thanks for answering on SO! Currently, your suggestion is indeed the way to go.

Incidentally, today I' ve read a blog post favoring [geoms over custom monolithic ggplot2 functions](http://blog.mjskay.com/2017/11/05/i-don-t-want-your-monolithic-ggplot-function/). While I agree, I can currently not commit enough time to implement this solution to customizing the plot.
