### ISSUE TITLE
Raystation DVH read fails 

### ISSUE THREAD

**Issue by H53-OOF** [dwoll/DVHmetrics#5]
I get the following error when trying to read in a DVH file from RayStation V12:

> Error in (function (strct, structVol, info)  : No DVH data found
In addition: Warning message:
In (function (strct, structVol, info)  :
  Could not determine dose measurement unit

DVH file is formatted as follows:
`#PatientName:123456
#PatientId:123456
#Dosename:Plan dose: MC (CT 1)
#RoiName:PTV
#Roi volume fraction outside grid: 0%
#Unit: cGy
0.000	100.000
27.641	100.000
55.281	100.000
82.922	100.000
110.563	100.000
138.203	100.000
165.844	100.000
193.485	100.000
221.125	100.000
248.766	100.000
276.407	100.000
304.047	100.000
331.688	100.000
359.329	100.000
386.969	100.000
414.610	100.000
442.251	100.000
469.891	100.000
497.532	100.000
525.173	100.000
552.813	100.000
580.454	100.000
608.095	100.000
635.735	100.000
663.376	100.000
691.017	100.000
718.657	100.000
746.298	100.000
773.939	100.000
801.579	100.000
829.220	100.000
856.861	100.000
884.501	100.000
912.142	100.000
939.782	100.000
967.423	100.000
995.064	100.000
1022.704	100.000
1050.345	100.000
1077.986	100.000
1105.626	100.000
1133.267	100.000
1160.908	100.000
1188.548	100.000
1216.189	100.000
1243.830	100.000
1271.470	100.000
1299.111	100.000
1326.752	100.000
1354.392	100.000
1382.033	100.000
1409.674	100.000
1437.314	100.000
1464.955	100.000
1492.596	100.000
1520.236	100.000
1547.877	100.000
1575.518	100.000
1603.158	100.000
1630.799	100.000
1658.440	100.000
1686.080	100.000
1713.721	100.000
1741.362	100.000
1769.002	100.000
1796.643	100.000
1824.284	100.000
1851.924	100.000
1879.565	100.000
1907.206	100.000
1934.846	100.000
1962.487	100.000
1990.128	100.000
2017.768	100.000
2045.409	100.000
2073.050	100.000
2100.690	100.000
2128.331	100.000
2155.972	100.000
2183.612	100.000
2211.253	100.000
2238.894	100.000
2266.534	100.000
2294.175	100.000
2321.816	100.000
2349.456	100.000
2377.097	100.000
2404.738	100.000
2432.378	100.000
2460.019	100.000
2487.660	100.000
2515.300	100.000
2542.941	100.000
2570.582	100.000
2598.222	100.000
2625.863	100.000
2653.504	100.000
2681.144	100.000
2708.785	100.000
2736.426	100.000
2764.066	100.000
2791.707	100.000
2819.347	100.000
2846.988	100.000
2874.629	100.000
2902.269	100.000
2929.910	100.000
2957.551	100.000
2985.191	100.000
3012.832	100.000
3040.473	100.000
3068.113	100.000
3095.754	100.000
3123.395	100.000
3151.035	100.000
3178.676	100.000
3206.317	100.000
3233.957	100.000
3261.598	100.000
3289.239	100.000
3316.879	100.000
3344.520	100.000
3372.161	100.000
3399.801	100.000
3427.442	100.000
3455.083	100.000
3482.723	100.000
3510.364	100.000
3538.005	100.000
3565.645	100.000
3593.286	100.000
3613.513	100.000
3620.927	100.000
3648.567	100.000
3676.208	99.996
3703.849	99.993
3731.489	99.986
3759.130	99.986
3786.771	99.972
3814.411	99.959
3842.052	99.950
3869.693	99.950
3897.333	99.935
3924.974	99.918
3952.615	99.910
3980.255	99.893
4007.896	99.866
4035.537	99.827
4063.177	99.809
4090.818	99.776
4118.459	99.752
4146.099	99.712
4173.740	99.697
4201.381	99.642
4229.021	99.625
4256.662	99.580
4284.303	99.558
4311.943	99.528
4335.874	99.500
4339.584	99.483
4367.225	99.408
4394.865	99.338
4422.506	99.307
4450.147	99.233
4477.787	99.180
4505.428	99.091
4531.868	99.000
4533.069	98.992
4560.709	98.891
4588.350	98.763
4615.990	98.606
4637.215	98.500
4643.631	98.467
4671.272	98.218
4694.981	98.000
4698.912	97.973
4726.553	97.710
4752.276	97.500
4754.194	97.486
4781.834	97.217
4799.786	97.000
4809.475	96.857
4835.676	96.500
4837.116	96.491
4863.981	96.000
4864.756	95.978
4885.873	95.500
4892.397	95.382
4909.256	95.000
4920.038	94.674
4925.926	94.500
4945.714	94.000
4947.678	93.933
4961.136	93.500
4975.319	93.078
4977.640	93.000
4990.953	92.500
5002.960	92.004
5003.049	92.000
5012.376	91.500
5022.115	91.000
5030.600	90.593
5032.919	90.500
5043.027	90.000
5051.278	89.500
5058.241	89.066
5059.066	89.000
5067.085	88.500
5073.182	88.000
5081.650	87.500
5085.882	87.126
5087.164	87.000
5093.221	86.500
5098.801	86.000
5105.062	85.500
5111.101	85.000
5113.522	84.707
5116.040	84.500
5120.690	84.000
5124.958	83.500
5129.338	83.000
5133.550	82.500
5138.505	82.000
5141.163	81.764
5143.574	81.500
5146.986	81.000
5150.966	80.500
5154.187	80.000
5158.274	79.500
5162.297	79.000
5165.825	78.500
5168.804	78.082
5169.403	78.000
5172.204	77.500
5175.298	77.000
5179.146	76.500
5182.495	76.000
5185.191	75.500
5187.609	75.000
5189.789	74.500
5192.416	74.000
5194.901	73.500
5196.444	73.239
5197.484	73.000
5199.427	72.500
5201.304	72.000
5203.347	71.500
5205.615	71.000
5207.950	70.500
5210.383	70.000
5212.335	69.500
5214.313	69.000
5216.372	68.500
5218.251	68.000
5220.145	67.500
5222.266	67.000
5223.996	66.500
5224.085	66.460
5225.929	66.000
5228.553	65.500
5230.234	65.000
5231.879	64.500
5233.843	64.000
5235.735	63.500
5237.726	63.000
5239.607	62.500
5241.354	62.000
5243.016	61.500
5244.594	61.000
5246.523	60.500
5248.056	60.000
5249.741	59.500
5251.726	59.003
5251.734	59.000
5253.600	58.500
5255.575	58.000
5257.205	57.500
5259.075	57.000
5260.744	56.500
5262.360	56.000
5264.030	55.500
5265.826	55.000
5267.147	54.500
5268.914	54.000
5270.289	53.500
5271.863	53.000
5273.954	52.500
5275.896	52.000
5278.088	51.500
5279.366	51.205
5280.256	51.000
5282.255	50.500
5283.878	50.000
5285.408	49.500
5287.005	49.000
5288.495	48.500
5290.065	48.000
5291.754	47.500
5293.330	47.000
5294.918	46.500
5296.613	46.000
5298.274	45.500
5300.108	45.000
5301.867	44.500
5303.564	44.000
5304.959	43.500
5306.490	43.000
5307.007	42.850
5308.194	42.500
5309.474	42.000
5311.400	41.500
5312.692	41.000
5314.444	40.500
5315.850	40.000
5317.661	39.500
5319.181	39.000
5321.002	38.500
5322.499	38.000
5324.105	37.500
5325.700	37.000
5327.378	36.500
5329.335	36.000
5331.231	35.500
5333.039	35.000
5334.648	34.538
5334.757	34.500
5336.697	34.000
5338.712	33.500
5340.196	33.000
5341.888	32.500
5343.425	32.000
5345.071	31.500
5347.021	31.000
5349.086	30.500
5351.257	30.000
5352.995	29.500
5354.808	29.000
5356.653	28.500
5358.342	28.000
5360.074	27.500
5361.840	27.000
5362.288	26.880
5364.194	26.500
5366.095	26.000
5367.798	25.500
5369.618	25.000
5371.273	24.500
5372.857	24.000
5374.521	23.500
5376.742	23.000
5378.254	22.500
5380.182	22.000
5381.989	21.500
5383.819	21.000
5385.643	20.500
5388.075	20.000
5389.747	19.500
5389.929	19.447
5391.471	19.000
5393.580	18.500
5395.245	18.000
5397.126	17.500
5399.220	17.000
5401.177	16.500
5403.018	16.000
5405.253	15.500
5407.485	15.000
5409.400	14.500
5411.079	14.000
5412.912	13.500
5414.662	13.000
5417.138	12.500
5417.570	12.440
5419.524	12.000
5421.659	11.500
5423.801	11.000
5425.830	10.500
5427.829	10.000
5429.580	9.500
5431.628	9.000
5433.388	8.500
5435.429	8.000
5437.725	7.500
5439.944	7.000
5441.849	6.500
5444.783	6.000
5445.210	5.908
5447.266	5.500
5449.552	5.000
5452.065	4.500
5454.810	4.000
5457.614	3.500
5460.664	3.000
5464.985	2.500
5470.234	2.000
5472.851	1.808
5477.519	1.500
5488.320	1.000
5500.492	0.541
5501.714	0.500
5528.132	0.000
5528.132	0.000
`
I assume the DVH format has been changed - are there any examples of acceptable DVH file formatting?

Thanks!

**Comment by dwoll** [comment]
Thanks for your interest in DVHmetrics! I assume that the data you pasted is actually on separate lines - one line for each header element starting with "#", then one line each for the two columns with DVH data. If that's the case, then it seems the only problem is line

```
#Unit: cGy
```

If I change this to

```
#Dose unit: cGy
```

The file can be imported (mind the upper case D and lower case u though). If you confirm that this works, I'll change the RayStation import routine to be more flexible when trying to find the dose unit line.
[dvh_raystation.txt](https://github.com/dwoll/DVHmetrics/files/9434508/dvh_raystation.txt)
.

**Comment by dwoll** [comment]
I've made a change to the import routine to account for changes in V12 export file formatting. Could you please check whether this fixes the issue? Thanks!

**Comment by H53-OOF** [comment]
Exchanging "#Unit:" for "#Dose unit:" does indeed solve the problem (must be done for all structures in the file.

I'm happy to test the changes in the import routine - how do I get the update, do I need to install a beta version?

**Comment by H53-OOF** [comment]
Additionally - using your dvh_raystation.txt and attempting to calculate NTCP as follows I get an error:

`test <- readDVH("dvh_raystation.txt", type = "RayStation")
getNTCP(test[[1]], NTCPtd50=40, NTCPm=0.6, NTCPn=0.5, NTCPtype="probit")`

Warning message:
In getEUD.DVHs(x, EUDa = EUDa, EUDfn = EUDfn, EUDab = EUDab) :
  Numerical problems encountered, NA returned

**Comment by dwoll** [comment]
Thanks for the feedback! You can install the development version of `DVHmetrics` from GitHub using package `remotes`.

```
install.packages("remotes")
remotes::install_github("dwoll/DVHmetrics")
```

I'll look at the NTCP issue separately, once it's safe to say that reading in works. EUD calculation involves exponentiation which carries the risk of producing too large numbers, especially for doses given in cGy, such as here.

**Comment by H53-OOF** [comment]
The DVH files read in successfully with the development version.

However, when printing a summary of the DVH contents I note the structure volumes are missing: 

DVH: Structure 'PTV' (? CC), Dose: 0-5500CGY
DVH: Structure 'CTV' (? CC), Dose: 0-5500CGY
DVH: Structure 'ITV' (? CC), Dose: 0-5500CGY

**Comment by dwoll** [comment]
RayStation does not export absolute structure volume, the only available information is percentage volume in the DVH. You have two options:

1. You can contact RayStation customer support about the issue. Earlier this year, another RayStation user informed me that the vendor enabled exporting an additional line such as `#RoiVolume:500`. Importing this information - if present - is already supported by DVHmetrics.
2. You can supply additional information to `readDVH()` to 'fill in the blanks' with manually provided data. The call then looks like this:

```
 x <- readDVH("g:/dvh_raystation.txt",
              type="RayStation",
              raystation=list(list(structVol=c(PTV=500),
                                   volumeUnit="CC",
                                   doseRx="5500 cGy")))
```

It's a bit clunky... Each structure needs to have an entry in the named vector with a structure name that exactly matches the names given in the `#RoiName:` lines. For an additional structure, the relevant code would look like `structVol=c(PTV=500, OAR_Heart=200)`

**Comment by rhj1993119** [comment]
> The DVH files read in successfully with the development version.
> 
> However, when printing a summary of the DVH contents I note the structure volumes are missing:
> 
> DVH: Structure 'PTV' (? CC), Dose: 0-5500CGY DVH: Structure 'CTV' (? CC), Dose: 0-5500CGY DVH: Structure 'ITV' (? CC), Dose: 0-5500CGY

Oh I am having the same issue as well
