### ISSUE TITLE
RayStation DVH

### ISSUE THREAD

**Issue by marmo2** [dwoll/DVHmetrics#6]
Hello,

 I am trying to read in a DVH file exported from RayStation 10B, which is in cumulative format with no absolute structure volumes included in it (see below snippet, older versions seem to be the same). I found in the manual that external info needs to be supplied for RayStation files. I was wondering what the formatting should look like for this external info and how is it linked to the DVH file. An example would be very helpful. Thanks in advance!

Maryam
[example_DVH.pdf](https://github.com/dwoll/DVHmetrics/files/10789435/example_DVH.pdf)

**Comment by dwoll** [comment]
Many thanks for helping improve DVHmetrics! I hadn't come across DVH files with RBE dose, so I had to slightly change the function that reads in RayStation files. Therefore, please try to install the current devel version:

```
## update DVHmetrics to devel version
## required just once
## "remotes" is a package that lets users install directly from GitHub
install.packages("remotes")
## install development version of DVHmetrics from GitHub
## when asked to update packages: in doubt, choose 3 for "None"
remotes::install_github("dwoll/DVHmetrics")
```

After that, the following should work with the attached DVH sample file. Note that the DVH columns need to be tab-separated - which was the case for past RayStation files I received. Also note that I copied the structure and renamed it to show how supplying information works for multiple structures. The structure names have to match those in the DVH file.

```
library(DVHmetrics)
fpath <- "c:/users/daniel/Downloads/raystatation_example.txt" # change this
x <- readDVH(fpath,
             type="RayStation",
             raystation=list(list(date="2023-02-21",
                                  doseRx="60Gy",
                                  volumeUnit="CC",
                                  structVol=c("Prostate"=150,
                                              "Other"=100))))

print(x, verbose=TRUE)
```

For reading in more than 1 file, there needs to be 1 supplementary info list for each file like so:

```
fpath <- c("path_to_file/raystation_file1.txt",
           "path_to_file/raystation_file2.txt")

x <- readDVH(fpath,
             type="RayStation",
             raystation=list(list(date="2022-01-01",
                                  doseRx="60Gy",
                                  volumeUnit="CC",
                                  structVol=c("Structure1"=150,
                                              "Structure2"=100)),
                             list(date="2022-01-01",
                                  doseRx="60Gy",
                                  volumeUnit="CC",
                                  structVol=c("Structure1"=150,
                                              "Structure2"=100))))
```

It's not elegant, but until RayStation provides that information in the DVH file, it's better than nothing I guess.

[raystatation_example.txt](https://github.com/dwoll/DVHmetrics/files/10792494/raystatation_example.txt)

**Comment by marmo2** [comment]
Thank you so much for your response! I just got a chance to try this out and it works perfectly!
I can't wait to explore all the functionalities of this package.

**Comment by dwoll** [comment]
Thanks for the feedback, glad it worked!
