### ISSUE TITLE
Same patients with different plans 

### ISSUE THREAD

**Issue by rhj1993119** [dwoll/DVHmetrics#8]
Hello, 
I have different plans for the same pateint. 
I get a warning, do you have any recommendation for dealing with several plans for one patient?
when I changed the patient id, I also get an error msg. 
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  scan() expected 'a real', got '"0.000'
In addition: Warning message:
In readLines(con = con) :
  incomplete final line found on '9_47971156dvh.csv'

Thanks!

**Comment by dwoll** [comment]
Hi, Thanks for your interest in DVHmetrics!

Indeed, as you point out, the handling of multiple plans per patient is currently not optimal. When reading in Eclipse files, you can set the option `readDVH("filename", type="Eclipse", courseAsID=TRUE)`. In that case, the `Course` field is appended with an underscore to the actual patient ID to ensure a unique ID. It would not be too difficult to extend this behavior to the `Plan` field if that's easier to control for you.

Another, arguably less convenient solution would be to edit the patient ID field yourself to make it unique.

Are you using Eclipse or anothe TPS?

Can you share part of the - anonymized - DVH file with the errror? Otherwise it's hard for me to guess what's wrong.

**Comment by rhj1993119** [comment]
Actually I am using both Raystation and Eclipse. I attached the two Raystation plans under one patient. Thanks for your help!

**Comment by rhj1993119** [comment]
[plan1.csv](https://github.com/dwoll/DVHmetrics/files/11881990/plan1.csv)
[plan2.csv](https://github.com/dwoll/DVHmetrics/files/11881991/plan2.csv)

**Comment by rhj1993119** [comment]
Oh, I just tried to open my Raystation file and it worked yesterday.. however, now when I import the Raystation file to R, I got an error msg  as follows:  Error in (function (strct, structVol, info)  : No DVH data found
In addition: Warning message:
In (function (strct, structVol, info)  :
  Could not determine dose measurement unit

**Comment by rhj1993119** [comment]
However, the eclipse plan totally works well. It is so weird that there was no problem opening the data few hours ago, but now it can't read suddenly :( ..  
===
I solve this issue by restaring R session.

**Comment by dwoll** [comment]
Thanks for the files! I will look into the issue, but it will take me a couple of days due to other things currently on my table.

**Comment by dwoll** [comment]
I reproduced the error. Inspecting the DVH files with a text editor, I noticed that the lines in the actual DVH sections are in quotes, and that lines end with a , . The RayStation files I have seen so far do not have quotes of , symbols - i.e., they are not actually CSV files. When I remove all quotes and , from the file (see attached), the process of reading in works. It still gives the warning about an incomplete last line, but that is inconsequential.

Did you open the DVH file in a spreadsheet program like Excel? If so, that might have changed the contents.

Does the attached diagram look reasonable?
![plan1](https://github.com/dwoll/DVHmetrics/assets/1952101/d7f3fc68-7b2b-4f7e-8983-0d0a86774b7d)

[rhj1993119_plan1_mod.csv](https://github.com/dwoll/DVHmetrics/files/11938521/rhj1993119_plan1_mod.csv)

**Comment by rhj1993119** [comment]
Thanks for your reply. Actually, when I import an file from Eclipse, the file format is .dvh and then I changed the file name to .txt or .csv. Then I opend it in Excel.  Would you recommend I only change the file format and not change anything? thanks

**Comment by dwoll** [comment]
Thanks for explaining your workflow! Indeed, I'd advise against opening the file in Exel. It is quite possible that when "seeing" the .csv extension, Excel tries to save it as syntactically correct csv, thus altering the file. If you want to - say - change the patient ID, you can use a plain text editor, such as Notepad++ (if you have a Windows computer).

**Comment by rhj1993119** [comment]
Thanks for your help! Yeah I should not open it in Excel
